# =========== Dotfiles  ===========
alias bi="brew install"
alias k="kubectl"
alias glog="git log"
alias gadd="git add"
alias gdev="git checkout dev"
alias gmaster="git checkout master"
alias ga="git commit --amend"
alias gcmt="git commit"
alias gpush="git push origin"
alias gpull="git pull --rebase origin"
alias gc="git checkout"
alias gst="git status"
alias gstash="git stash"
alias grebase="git rebase"
alias gr="git rebase"
# =========== End Dotfiles ===========
